# Generated by Django 4.2.2 on 2023-08-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_offer', '0003_offer'),
        ('app_products', '0003_product_images_alter_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_offer.offer'),
        ),
    ]
