# Generated by Django 4.2.2 on 2023-07-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=255)),
                ('Author_quotes', models.TextField()),
                ('Author_description', models.TextField()),
                ('Author_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
