# Generated by Django 4.2.2 on 2023-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='Author_birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='Author_nation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='Author_quotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
