# Generated by Django 4.2.2 on 2023-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authors', '0002_authors_author_birth_year_authors_author_nation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='Author_birth_year',
            new_name='author_birth_year',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='Author_description',
            new_name='author_description',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='Author_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='Author_nation',
            new_name='author_nation',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='Author_quotes',
            new_name='author_quotes',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='Author_image',
        ),
        migrations.AddField(
            model_name='authors',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='phottos/authors'),
        ),
    ]
