# Generated by Django 4.2.2 on 2023-07-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authors', '0004_authors_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='slug',
        ),
    ]
