# Generated by Django 4.2.2 on 2023-08-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_alter_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
