# Generated by Django 4.2.2 on 2023-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0007_alter_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
