# Generated by Django 4.2.2 on 2023-07-30 13:05

import app_offer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=15)),
                ('min_amount', models.PositiveBigIntegerField()),
                ('off_percent', models.PositiveBigIntegerField()),
                ('max_discount', models.PositiveBigIntegerField()),
                ('expiry_date', models.DateField(validators=[app_offer.models.validate_expiry_date])),
            ],
        ),
    ]
