# Generated by Django 4.2.2 on 2023-08-01 08:44

import app_offer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offer', '0002_coupon_coupon_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('off_percent', models.PositiveBigIntegerField()),
                ('start_date', models.DateField(validators=[app_offer.models.validate_expiry_date])),
                ('end_date', models.DateField()),
            ],
        ),
    ]
