# Generated by Django 4.2.2 on 2023-07-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_alter_product_category'),
        ('app_category', '0002_category_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
