# Generated by Django 4.2.2 on 2023-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0003_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_list',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
